const mongoose=require('mongoose');
const userSchema=new mongoose.Schema({
    firstName:{
        type:String,
        required:true,
        trim:true
    },
    lastName:{
        type:String,
        required:true,
        trim:true
    },
    middleName:{
        type:String,
        required:true,
        trim:true
    },
    address:{
        type:String,
        required:true,
        trim:true
    },
    birthDate:{
        type:Date,
        required:true,
        trim:true
    },
    userImage:{
        type:String,
        required:true,
        trim:true
    },
    email:{
        type:String,
        required:true,
        trim:true
    },
    password:{
        type:String,
        required:true,
        trim:true
    },
    token:{
        type:String,
        required:true,
        trim:true
    }
},
    {
        timestamps:true
    }
)

module.exports=mongoose.model('User',userSchema)